name: team-skeleton2010-homepage
app: node@16
options:
  install: npm ci --production
  env:
    - name: MAIL_PSWORD
      value: rvtmsujymfscgfru
    - name: MAIL_USER
      value: inseong747@gmail.com
    - name: PORT
      value: 3000
  ports: 3000
  start: npm start
context:
  git:
    url: https://github.com/skeleton2010/team-inseong-homepage.git
    branch: master